version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: safehouse_db
      POSTGRES_USER: hao
      POSTGRES_PASSWORD: utfpr
    ports:
      - "5432:5432"
